[project]
name = "bitcoin_python"
version = "0.1.0"
description = "A simple implementation of Bitcoin's elliptic curve cryptography in pure Python."
requires-python = ">=3.11"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
